#docker build -t github-search-frontend:latest .
#docker run -p 3000:3000 github-search-frontend

## This is a mulitstage docker build
#1. Builder container : contains all the code and dependencies
#2. Static container: contains all the static code which will be served by nginx

#STEP 1 - builder stage
FROM node:12 as github-searcher-build
LABEL maintainer="sandeep"
LABEL product="Github-Searcher-Frontend"

#create directories
RUN mkdir frontend

# switch to frontend
WORKDIR /frontend

#clone all the code
copy ./package.json .
COPY ./Dockerfile.dev .
COPY ./.env .

#Install env-cmd at system level, so that env can be available to the react application
RUN npm install -g env-cmd

#install all the dependencies
RUN yarn install

#copy tsconfig settings
COPY ./tsconfig.json .
COPY ./tsconfig.paths.json .
COPY ./yarn.lock .

#create src directory
RUN mkdir /frontend/src

#copy source
COPY ./src/ /frontend/src

#create public directory
RUN mkdir /frontend/public

#copy public files
COPY ./public/ /frontend/public

#start the react app
CMD ["yarn", "run", "start"]